#+TITLE: evil.el

* <Leader>

Enable evil-leader in every buffer where evil-mode is enabled.

#+BEGIN_SRC emacs-lisp
(require 'evil-leader)
(global-evil-leader-mode)
#+END_SRC

We do this *before* enabling evil-mode so that evil-leader will be
available in the buffers created on startup (e.g., *scratch*,
*Messages*).

Use Spacebar as <Leader>.

#+BEGIN_SRC emacs-lisp
(evil-leader/set-leader "<SPC>")
#+END_SRC

* Turn on evil-mode

#+BEGIN_SRC emacs-lisp
  (require 'evil)
  (evil-mode 1)
#+END_SRC

* Editing

** Unfill paragraph

Undo line-wrapping by removing line breaks.

#+BEGIN_SRC emacs-lisp
    (defun unfill-paragraph (&optional region)
      "Takes a multiline paragraph and removes the line breaks"
      (interactive)
      (let ((fill-column (point-max)))
        (fill-paragraph nil region)))

    (evil-leader/set-key
     "q" 'unfill-paragraph)
#+END_SRC

** Use 'jk' as <Esc>

Uses key-chord mode to define 'jk' as a keychord bound to <Esc>.

#+BEGIN_SRC emacs-lisp
(require 'key-chord)
(key-chord-mode 1)
(key-chord-define evil-insert-state-map  "jk" 'evil-normal-state)
#+END_SRC

* Buffer and Window Manipulation

Default behavior for =:q= is to kill the Emacs frame. I almost never
do that, so instead I'll use it to kill the buffer.

#+BEGIN_SRC emacs-lisp
  (evil-ex-define-cmd "q" 'evil-delete-buffer)
#+END_SRC

Use =:e= in place of =C-x C-f=.

#+BEGIN_SRC emacs-lisp
  (evil-ex-define-cmd "edit" 'helm-find-files)
#+END_SRC

Use =:x= for =M-x=.

#+BEGIN_SRC emacs-lisp
  (evil-ex-define-cmd "x" 'helm-M-x)
#+END_SRC

Use =:b= for =M-x b=

#+BEGIN_SRC emacs-lisp
  (evil-ex-define-cmd "b" 'switch-to-buffer)
#+END_SRC

Use =<leader> w= for window commands.

#+BEGIN_SRC emacs-lisp
(evil-leader/set-key "wk" 'evil-window-up)
(evil-leader/set-key "wj" 'evil-window-down)
(evil-leader/set-key "wh" 'evil-window-left)
(evil-leader/set-key "wl" 'evil-window-right)
#+END_SRC

* Escaping Evil Mode

Some modes just don't play well with Evil mode. For these, just revert
to normal Emacs editing. (Stolen from [[https://github.com/bling/dotemacs/blob/master/config/init-evil.el][here]]).

#+BEGIN_SRC emacs-lisp
    (defcustom dotemacs-evil/emacs-state-modes
      '(edebug-mode
        git-commit-mode
        magit-blame-mode
        Info-mode)
      "List of modes that when active should switch to Emacs state."
      :type '(repeat (symbol))
      :group 'dotemacs-evil)

#+END_SRC

#+RESULTS:
: dotemacs-evil/emacs-state-modes

#+BEGIN_SRC emacs-lisp
  (require 'cl-macs)
  (cl-loop for mode in dotemacs-evil/emacs-state-modes
           do (let ((hook (concat (symbol-name mode) "-hook")))
                (add-hook (intern hook) `(lambda ()
                                           (turn-off-evil-mode)))))
#+END_SRC

#+RESULTS:
